<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Mayur" ignored="0" name="RetryTest" tests="6" failures="2" timestamp="2022-10-25T11:59:24 IST" time="0.195" errors="0">
  <testcase name="testCase1" time="0.022" classname="runFailedTCTestNg.SampleTestCase">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase1" time="0.0" classname="runFailedTCTestNg.SampleTestCase">
    <skipped/>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase1" time="0.0" classname="runFailedTCTestNg.SampleTestCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runFailedTCTestNg.SampleTestCase.testCase1(SampleTestCase.java:12)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase2" time="0.009" classname="runFailedTCTestNg.SampleTestCase">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="0.0" classname="runFailedTCTestNg.SampleTestCase">
    <skipped/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase2" time="0.015" classname="runFailedTCTestNg.SampleTestCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runFailedTCTestNg.SampleTestCase.testCase2(SampleTestCase.java:19)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- RetryTest -->
